name: 'Detect Changes in ParlaMint Repository'
#description: ''
inputs:
  repo_token:
    description: 'contains repository secret token'
    required: false
outputs:
  parla_process:
    description: "Parliaments that should be processes (is affected by change script or parliament change)"
    value: '${{ steps.detect-changes.outputs.parla_process }}'
  parla_all:
    description: "List of all Parliaments"
    value: '${{ steps.detect-changes.outputs.parla_all }}'
  parla_changed:
    description: "List of changed Parliaments"
    value: '${{ steps.detect-changes.outputs.parla_changed }}'
runs:
  using: "composite"
  steps:
    - name: Test if prereqs are installed
      run: |
          echo TODO
          echo "test if fetch == 2"
      shell: bash
    - name: Detect Changes
      run: |
          pwd
          cd ParlaMint
          pwd
          changed_files=$(git diff --name-only HEAD HEAD~1)
          echo A "$changed_files"
          echo "$changed_files"
          echo "$changed_files"|grep 'ParlaMint-.*/'
          echo "$changed_files"|grep 'ParlaMint-.*/'|sed 's/^ParlaMint-\([-A-Z]*\).*$/\1/'
          echo "$changed_files"|grep 'ParlaMint-.*/'|sed 's/^ParlaMint-\([-A-Z]*\).*$/\1/'|sort
          echo "$changed_files"|grep 'ParlaMint-.*/'|sed 's/^ParlaMint-\([-A-Z]*\).*$/\1/'|sort|uniq
          echo "$changed_files"|grep 'ParlaMint-.*/'|sed 's/^ParlaMint-\([-A-Z]*\).*$/\1/'|sort|uniq|tr '\n' ' '
          parla_changed=$(echo "$changed_files"|grep 'ParlaMint-.*/'|sed 's/^ParlaMint-\([-A-Z]*\).*$/\1/'|sort|uniq|tr '\n' ' ')
          echo B "$parla_changed"
          scripts_changed=$(echo "$changed_files"|grep -vc 'ParlaMint-.*')
          echo C
          parla_all=$(echo ParlaMint-*|sed 's/ParlaMint-\([-A-Z]*\)/\1/g'|sort)
          echo D
          parla_process=$(test -z "${parla_changed}" && echo "${parla_all}" || echo "${parla_changed}")
          echo E
          parla_process=$(echo "[\"$parla_process\"]"|sed 's/  */","/g')
          echo F
          parla_changed=$(echo "[\"$parla_changed\"]"|sed 's/  */","/g')
          echo G
          echo "DEBUG: changed_files=${changed_files}"
          echo A
          echo "DEBUG: parla_changed=${parla_changed}"
          echo A
          echo "DEBUG: scripts_changed=${scripts_changed}"
          echo A
          echo "DEBUG: parla_all=${parla_all}"
          echo A
          echo ::set-output name=parla_process::${parla_process}
          echo A
          echo ::set-output name=parla_all::${parla_all}
          echo A
          echo ::set-output name=parla_changed::${parla_changed}
      shell: bash
